// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auth.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_admin      Role = 0
	Role_viewer     Role = 1
	Role_superadmin Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "admin",
		1: "viewer",
		2: "superadmin",
	}
	Role_value = map[string]int32{
		"admin":      0,
		"viewer":     1,
		"superadmin": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequiresOtp   bool                   `protobuf:"varint,5,opt,name=requires_otp,json=requiresOtp,proto3" json:"requires_otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginRequest) GetRequiresOtp() bool {
	if x != nil {
		return x.RequiresOtp
	}
	return false
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=nodepb.Role" json:"role,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	RequiresOtp   bool                   `protobuf:"varint,6,opt,name=requires_otp,json=requiresOtp,proto3" json:"requires_otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_admin
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetRequiresOtp() bool {
	if x != nil {
		return x.RequiresOtp
	}
	return false
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nom           string                 `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Telephone     string                 `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	MotDePasse    string                 `protobuf:"bytes,6,opt,name=mot_de_passe,json=motDePasse,proto3" json:"mot_de_passe,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	PhotoProfil   string                 `protobuf:"bytes,10,opt,name=photo_profil,json=photoProfil,proto3" json:"photo_profil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *RegisterRequest) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RegisterRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *RegisterRequest) GetMotDePasse() string {
	if x != nil {
		return x.MotDePasse
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterRequest) GetPhotoProfil() string {
	if x != nil {
		return x.PhotoProfil
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	LoginId       string                 `protobuf:"bytes,4,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	Nom           string                 `protobuf:"bytes,2,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,3,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string                 `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Role          Role                   `protobuf:"varint,6,opt,name=role,proto3,enum=nodepb.Role" json:"role,omitempty"`
	MotDePasse    string                 `protobuf:"bytes,8,opt,name=mot_de_passe,json=motDePasse,proto3" json:"mot_de_passe,omitempty"`
	PhotoProfil   string                 `protobuf:"bytes,9,opt,name=photo_profil,json=photoProfil,proto3" json:"photo_profil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

func (x *UpdateUserRequest) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *UpdateUserRequest) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_admin
}

func (x *UpdateUserRequest) GetMotDePasse() string {
	if x != nil {
		return x.MotDePasse
	}
	return ""
}

func (x *UpdateUserRequest) GetPhotoProfil() string {
	if x != nil {
		return x.PhotoProfil
	}
	return ""
}

type CheckUserExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsRequest) Reset() {
	*x = CheckUserExistsRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsRequest) ProtoMessage() {}

func (x *CheckUserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckUserExistsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CheckUserExistsRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

type CheckUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsResponse) Reset() {
	*x = CheckUserExistsResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsResponse) ProtoMessage() {}

func (x *CheckUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CheckUserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *TokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyOTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotifyNewDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	DeviceInfo    string                 `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewDeviceRequest) Reset() {
	*x = NotifyNewDeviceRequest{}
	mi := &file_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewDeviceRequest) ProtoMessage() {}

func (x *NotifyNewDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewDeviceRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewDeviceRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{18}
}

func (x *NotifyNewDeviceRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *NotifyNewDeviceRequest) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

type NotifyNewDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewDeviceResponse) Reset() {
	*x = NotifyNewDeviceResponse{}
	mi := &file_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewDeviceResponse) ProtoMessage() {}

func (x *NotifyNewDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewDeviceResponse.ProtoReflect.Descriptor instead.
func (*NotifyNewDeviceResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{19}
}

func (x *NotifyNewDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetRequest) Reset() {
	*x = PasswordResetRequest{}
	mi := &file_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetRequest) ProtoMessage() {}

func (x *PasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetRequest.ProtoReflect.Descriptor instead.
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{20}
}

func (x *PasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetResponse) Reset() {
	*x = PasswordResetResponse{}
	mi := &file_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetResponse) ProtoMessage() {}

func (x *PasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetResponse.ProtoReflect.Descriptor instead.
func (*PasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{21}
}

func (x *PasswordResetResponse) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *PasswordResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnableMFARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableMFARequest) Reset() {
	*x = EnableMFARequest{}
	mi := &file_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableMFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableMFARequest) ProtoMessage() {}

func (x *EnableMFARequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableMFARequest.ProtoReflect.Descriptor instead.
func (*EnableMFARequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{22}
}

func (x *EnableMFARequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EnableMFAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableMFAResponse) Reset() {
	*x = EnableMFAResponse{}
	mi := &file_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableMFAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableMFAResponse) ProtoMessage() {}

func (x *EnableMFAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableMFAResponse.ProtoReflect.Descriptor instead.
func (*EnableMFAResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{23}
}

func (x *EnableMFAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisableMFARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMFARequest) Reset() {
	*x = DisableMFARequest{}
	mi := &file_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMFARequest) ProtoMessage() {}

func (x *DisableMFARequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMFARequest.ProtoReflect.Descriptor instead.
func (*DisableMFARequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{24}
}

func (x *DisableMFARequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DisableMFAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMFAResponse) Reset() {
	*x = DisableMFAResponse{}
	mi := &file_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMFAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMFAResponse) ProtoMessage() {}

func (x *DisableMFAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMFAResponse.ProtoReflect.Descriptor instead.
func (*DisableMFAResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{25}
}

func (x *DisableMFAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateUserPasswordRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

func (x *UpdateUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdateUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordResponse) Reset() {
	*x = UpdateUserPasswordResponse{}
	mi := &file_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordResponse) ProtoMessage() {}

func (x *UpdateUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{28}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{29}
}

func (x *ForgotPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{30}
}

func (x *GetUserProfileRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	Nom           string                 `protobuf:"bytes,2,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,3,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhotoProfil   string                 `protobuf:"bytes,5,opt,name=photo_profil,json=photoProfil,proto3" json:"photo_profil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserProfileResponse) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

func (x *GetUserProfileResponse) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *GetUserProfileResponse) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *GetUserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProfileResponse) GetPhotoProfil() string {
	if x != nil {
		return x.PhotoProfil
	}
	return ""
}

type SetCdnPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCdnPermissionsRequest) Reset() {
	*x = SetCdnPermissionsRequest{}
	mi := &file_auth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCdnPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCdnPermissionsRequest) ProtoMessage() {}

func (x *SetCdnPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCdnPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetCdnPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{32}
}

func (x *SetCdnPermissionsRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

func (x *SetCdnPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetCdnPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCdnPermissionsResponse) Reset() {
	*x = SetCdnPermissionsResponse{}
	mi := &file_auth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCdnPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCdnPermissionsResponse) ProtoMessage() {}

func (x *SetCdnPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCdnPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetCdnPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{33}
}

func (x *SetCdnPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nom           string                 `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Telephone     string                 `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_auth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{34}
}

func (x *CreateAdminRequest) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *CreateAdminRequest) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *CreateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *CreateAdminRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *CreateAdminRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateAdminRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminResponse) Reset() {
	*x = CreateAdminResponse{}
	mi := &file_auth_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminResponse) ProtoMessage() {}

func (x *CreateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminResponse.ProtoReflect.Descriptor instead.
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{35}
}

func (x *CreateAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAdminInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	Nom           string                 `protobuf:"bytes,2,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,3,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string                 `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminInfoResponse) Reset() {
	*x = GetAdminInfoResponse{}
	mi := &file_auth_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminInfoResponse) ProtoMessage() {}

func (x *GetAdminInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAdminInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{36}
}

func (x *GetAdminInfoResponse) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

func (x *GetAdminInfoResponse) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *GetAdminInfoResponse) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *GetAdminInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAdminInfoResponse) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *GetAdminInfoResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListAllAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllAdminsRequest) Reset() {
	*x = ListAllAdminsRequest{}
	mi := &file_auth_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllAdminsRequest) ProtoMessage() {}

func (x *ListAllAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAllAdminsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{37}
}

func (x *ListAllAdminsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAllAdminsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAllAdminsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListAllAdminsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAllAdminsRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListAllAdminsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Admins        []*GetAdminInfoResponse `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllAdminsResponse) Reset() {
	*x = ListAllAdminsResponse{}
	mi := &file_auth_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllAdminsResponse) ProtoMessage() {}

func (x *ListAllAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllAdminsResponse.ProtoReflect.Descriptor instead.
func (*ListAllAdminsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{38}
}

func (x *ListAllAdminsResponse) GetAdmins() []*GetAdminInfoResponse {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *ListAllAdminsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAdminByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilisateurId string                 `protobuf:"bytes,1,opt,name=utilisateur_id,json=utilisateurId,proto3" json:"utilisateur_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminByIDRequest) Reset() {
	*x = GetAdminByIDRequest{}
	mi := &file_auth_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminByIDRequest) ProtoMessage() {}

func (x *GetAdminByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAdminByIDRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{39}
}

func (x *GetAdminByIDRequest) GetUtilisateurId() string {
	if x != nil {
		return x.UtilisateurId
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x06nodepb\x1a\x1cgoogle/api/annotations.proto\"\xab\x01\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12!\n" +
	"\frequires_otp\x18\x05 \x01(\bR\vrequiresOtp\"\xc1\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\x04role\x18\x04 \x01(\x0e2\f.nodepb.RoleR\x04role\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\tR\x06userId\x12!\n" +
	"\frequires_otp\x18\x06 \x01(\bR\vrequiresOtp\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xde\x01\n" +
	"\x0fRegisterRequest\x12\x10\n" +
	"\x03nom\x18\x01 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x02 \x01(\tR\x06prenom\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1c\n" +
	"\ttelephone\x18\x05 \x01(\tR\ttelephone\x12 \n" +
	"\fmot_de_passe\x18\x06 \x01(\tR\n" +
	"motDePasse\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12!\n" +
	"\fphoto_profil\x18\n" +
	" \x01(\tR\vphotoProfil\"y\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x19\n" +
	"\blogin_id\x18\x04 \x01(\tR\aloginId\"\xff\x01\n" +
	"\x11UpdateUserRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\x12\x10\n" +
	"\x03nom\x18\x02 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x03 \x01(\tR\x06prenom\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1c\n" +
	"\ttelephone\x18\x05 \x01(\tR\ttelephone\x12 \n" +
	"\x04role\x18\x06 \x01(\x0e2\f.nodepb.RoleR\x04role\x12 \n" +
	"\fmot_de_passe\x18\b \x01(\tR\n" +
	"motDePasse\x12!\n" +
	"\fphoto_profil\x18\t \x01(\tR\vphotoProfil\"?\n" +
	"\x16CheckUserExistsRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\"1\n" +
	"\x17CheckUserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\".\n" +
	"\x12UpdateUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x11DeleteUserRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\"H\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Q\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x10VerifyOTPRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"-\n" +
	"\x11VerifyOTPResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x16NotifyNewDeviceRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1f\n" +
	"\vdevice_info\x18\x02 \x01(\tR\n" +
	"deviceInfo\"3\n" +
	"\x17NotifyNewDeviceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x14PasswordResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"C\n" +
	"\x15PasswordResetResponse\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x10EnableMFARequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"-\n" +
	"\x11EnableMFAResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x11DisableMFARequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\".\n" +
	"\x12DisableMFAResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"e\n" +
	"\x19UpdateUserPasswordRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"6\n" +
	"\x1aUpdateUserPasswordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\x15GetUserProfileRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\"\xa2\x01\n" +
	"\x16GetUserProfileResponse\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\x12\x10\n" +
	"\x03nom\x18\x02 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x03 \x01(\tR\x06prenom\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphoto_profil\x18\x05 \x01(\tR\vphotoProfil\"c\n" +
	"\x18SetCdnPermissionsRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"5\n" +
	"\x19SetCdnPermissionsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbe\x01\n" +
	"\x12CreateAdminRequest\x12\x10\n" +
	"\x03nom\x18\x01 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x02 \x01(\tR\x06prenom\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1c\n" +
	"\ttelephone\x18\x05 \x01(\tR\ttelephone\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\"/\n" +
	"\x13CreateAdminResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x14GetAdminInfoResponse\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId\x12\x10\n" +
	"\x03nom\x18\x02 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x03 \x01(\tR\x06prenom\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1c\n" +
	"\ttelephone\x18\x05 \x01(\tR\ttelephone\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\x94\x01\n" +
	"\x14ListAllAdminsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"c\n" +
	"\x15ListAllAdminsResponse\x124\n" +
	"\x06admins\x18\x01 \x03(\v2\x1c.nodepb.GetAdminInfoResponseR\x06admins\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"<\n" +
	"\x13GetAdminByIDRequest\x12%\n" +
	"\x0eutilisateur_id\x18\x01 \x01(\tR\rutilisateurId*-\n" +
	"\x04Role\x12\t\n" +
	"\x05admin\x10\x00\x12\n" +
	"\n" +
	"\x06viewer\x10\x01\x12\x0e\n" +
	"\n" +
	"superadmin\x10\x022\xcb\x10\n" +
	"\vAuthService\x12O\n" +
	"\x05Login\x12\x14.nodepb.LoginRequest\x1a\x15.nodepb.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12S\n" +
	"\x06Logout\x12\x15.nodepb.LogoutRequest\x1a\x16.nodepb.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12]\n" +
	"\vCreateAdmin\x12\x1a.nodepb.CreateAdminRequest\x1a\x1b.nodepb.CreateAdminResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/admins\x12o\n" +
	"\n" +
	"UpdateUser\x12\x19.nodepb.UpdateUserRequest\x1a\x1a.nodepb.UpdateUserResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/auth/users/{utilisateur_id}\x12\x82\x01\n" +
	"\x0fCheckUserExists\x12\x1e.nodepb.CheckUserExistsRequest\x1a\x1f.nodepb.CheckUserExistsResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/auth/users/{utilisateur_id}/exists\x12l\n" +
	"\n" +
	"DeleteUser\x12\x19.nodepb.DeleteUserRequest\x1a\x1a.nodepb.DeleteUserResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/auth/users/{utilisateur_id}\x12`\n" +
	"\rValidateToken\x12\x14.nodepb.TokenRequest\x1a\x15.nodepb.TokenResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/auth/validate-token\x12l\n" +
	"\fRefreshToken\x12\x1b.nodepb.RefreshTokenRequest\x1a\x1c.nodepb.RefreshTokenResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/refresh-token\x12`\n" +
	"\tVerifyOTP\x12\x18.nodepb.VerifyOTPRequest\x1a\x19.nodepb.VerifyOTPResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/auth/verify-otp\x12u\n" +
	"\x0fNotifyNewDevice\x12\x1e.nodepb.NotifyNewDeviceRequest\x1a\x1f.nodepb.NotifyNewDeviceResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/notify-device\x12\x7f\n" +
	"\x14RequestPasswordReset\x12\x1c.nodepb.PasswordResetRequest\x1a\x1d.nodepb.PasswordResetResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/auth/request-password-reset\x12`\n" +
	"\tEnableMFA\x12\x18.nodepb.EnableMFARequest\x1a\x19.nodepb.EnableMFAResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/auth/enable-mfa\x12d\n" +
	"\n" +
	"DisableMFA\x12\x19.nodepb.DisableMFARequest\x1a\x1a.nodepb.DisableMFAResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/auth/disable-mfa\x12{\n" +
	"\x12UpdateUserPassword\x12!.nodepb.UpdateUserPasswordRequest\x1a\".nodepb.UpdateUserPasswordResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/users/password\x12\x80\x01\n" +
	"\x0eGetUserProfile\x12\x1d.nodepb.GetUserProfileRequest\x1a\x1e.nodepb.GetUserProfileResponse\"/\x82\xd3\xe4\x93\x02)\x12'/v1/auth/users/{utilisateur_id}/profile\x12v\n" +
	"\x0eForgotPassword\x12\x1d.nodepb.ForgotPasswordRequest\x1a\x1e.nodepb.ForgotPasswordResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/users/forgot-password\x12\x96\x01\n" +
	"\x11SetCdnPermissions\x12 .nodepb.SetCdnPermissionsRequest\x1a!.nodepb.SetCdnPermissionsResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/admin/cdn-admins/{utilisateur_id}/permissions\x12`\n" +
	"\rListAllAdmins\x12\x1c.nodepb.ListAllAdminsRequest\x1a\x1d.nodepb.ListAllAdminsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/admins\x12n\n" +
	"\fGetAdminByID\x12\x1b.nodepb.GetAdminByIDRequest\x1a\x1c.nodepb.GetAdminInfoResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/admins/{utilisateur_id}BDZBgithub.com/thekrauss/Mini-CDN-DDoS-Lab-with-Go/control-plane/protob\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_auth_proto_goTypes = []any{
	(Role)(0),                          // 0: nodepb.Role
	(*LoginRequest)(nil),               // 1: nodepb.LoginRequest
	(*LoginResponse)(nil),              // 2: nodepb.LoginResponse
	(*LogoutRequest)(nil),              // 3: nodepb.LogoutRequest
	(*LogoutResponse)(nil),             // 4: nodepb.LogoutResponse
	(*RegisterRequest)(nil),            // 5: nodepb.RegisterRequest
	(*RegisterResponse)(nil),           // 6: nodepb.RegisterResponse
	(*UpdateUserRequest)(nil),          // 7: nodepb.UpdateUserRequest
	(*CheckUserExistsRequest)(nil),     // 8: nodepb.CheckUserExistsRequest
	(*CheckUserExistsResponse)(nil),    // 9: nodepb.CheckUserExistsResponse
	(*UpdateUserResponse)(nil),         // 10: nodepb.UpdateUserResponse
	(*DeleteUserRequest)(nil),          // 11: nodepb.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 12: nodepb.DeleteUserResponse
	(*TokenRequest)(nil),               // 13: nodepb.TokenRequest
	(*TokenResponse)(nil),              // 14: nodepb.TokenResponse
	(*RefreshTokenRequest)(nil),        // 15: nodepb.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 16: nodepb.RefreshTokenResponse
	(*VerifyOTPRequest)(nil),           // 17: nodepb.VerifyOTPRequest
	(*VerifyOTPResponse)(nil),          // 18: nodepb.VerifyOTPResponse
	(*NotifyNewDeviceRequest)(nil),     // 19: nodepb.NotifyNewDeviceRequest
	(*NotifyNewDeviceResponse)(nil),    // 20: nodepb.NotifyNewDeviceResponse
	(*PasswordResetRequest)(nil),       // 21: nodepb.PasswordResetRequest
	(*PasswordResetResponse)(nil),      // 22: nodepb.PasswordResetResponse
	(*EnableMFARequest)(nil),           // 23: nodepb.EnableMFARequest
	(*EnableMFAResponse)(nil),          // 24: nodepb.EnableMFAResponse
	(*DisableMFARequest)(nil),          // 25: nodepb.DisableMFARequest
	(*DisableMFAResponse)(nil),         // 26: nodepb.DisableMFAResponse
	(*UpdateUserPasswordRequest)(nil),  // 27: nodepb.UpdateUserPasswordRequest
	(*UpdateUserPasswordResponse)(nil), // 28: nodepb.UpdateUserPasswordResponse
	(*ForgotPasswordRequest)(nil),      // 29: nodepb.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),     // 30: nodepb.ForgotPasswordResponse
	(*GetUserProfileRequest)(nil),      // 31: nodepb.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),     // 32: nodepb.GetUserProfileResponse
	(*SetCdnPermissionsRequest)(nil),   // 33: nodepb.SetCdnPermissionsRequest
	(*SetCdnPermissionsResponse)(nil),  // 34: nodepb.SetCdnPermissionsResponse
	(*CreateAdminRequest)(nil),         // 35: nodepb.CreateAdminRequest
	(*CreateAdminResponse)(nil),        // 36: nodepb.CreateAdminResponse
	(*GetAdminInfoResponse)(nil),       // 37: nodepb.GetAdminInfoResponse
	(*ListAllAdminsRequest)(nil),       // 38: nodepb.ListAllAdminsRequest
	(*ListAllAdminsResponse)(nil),      // 39: nodepb.ListAllAdminsResponse
	(*GetAdminByIDRequest)(nil),        // 40: nodepb.GetAdminByIDRequest
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: nodepb.LoginResponse.role:type_name -> nodepb.Role
	0,  // 1: nodepb.UpdateUserRequest.role:type_name -> nodepb.Role
	37, // 2: nodepb.ListAllAdminsResponse.admins:type_name -> nodepb.GetAdminInfoResponse
	1,  // 3: nodepb.AuthService.Login:input_type -> nodepb.LoginRequest
	3,  // 4: nodepb.AuthService.Logout:input_type -> nodepb.LogoutRequest
	35, // 5: nodepb.AuthService.CreateAdmin:input_type -> nodepb.CreateAdminRequest
	7,  // 6: nodepb.AuthService.UpdateUser:input_type -> nodepb.UpdateUserRequest
	8,  // 7: nodepb.AuthService.CheckUserExists:input_type -> nodepb.CheckUserExistsRequest
	11, // 8: nodepb.AuthService.DeleteUser:input_type -> nodepb.DeleteUserRequest
	13, // 9: nodepb.AuthService.ValidateToken:input_type -> nodepb.TokenRequest
	15, // 10: nodepb.AuthService.RefreshToken:input_type -> nodepb.RefreshTokenRequest
	17, // 11: nodepb.AuthService.VerifyOTP:input_type -> nodepb.VerifyOTPRequest
	19, // 12: nodepb.AuthService.NotifyNewDevice:input_type -> nodepb.NotifyNewDeviceRequest
	21, // 13: nodepb.AuthService.RequestPasswordReset:input_type -> nodepb.PasswordResetRequest
	23, // 14: nodepb.AuthService.EnableMFA:input_type -> nodepb.EnableMFARequest
	25, // 15: nodepb.AuthService.DisableMFA:input_type -> nodepb.DisableMFARequest
	27, // 16: nodepb.AuthService.UpdateUserPassword:input_type -> nodepb.UpdateUserPasswordRequest
	31, // 17: nodepb.AuthService.GetUserProfile:input_type -> nodepb.GetUserProfileRequest
	29, // 18: nodepb.AuthService.ForgotPassword:input_type -> nodepb.ForgotPasswordRequest
	33, // 19: nodepb.AuthService.SetCdnPermissions:input_type -> nodepb.SetCdnPermissionsRequest
	38, // 20: nodepb.AuthService.ListAllAdmins:input_type -> nodepb.ListAllAdminsRequest
	40, // 21: nodepb.AuthService.GetAdminByID:input_type -> nodepb.GetAdminByIDRequest
	2,  // 22: nodepb.AuthService.Login:output_type -> nodepb.LoginResponse
	4,  // 23: nodepb.AuthService.Logout:output_type -> nodepb.LogoutResponse
	36, // 24: nodepb.AuthService.CreateAdmin:output_type -> nodepb.CreateAdminResponse
	10, // 25: nodepb.AuthService.UpdateUser:output_type -> nodepb.UpdateUserResponse
	9,  // 26: nodepb.AuthService.CheckUserExists:output_type -> nodepb.CheckUserExistsResponse
	12, // 27: nodepb.AuthService.DeleteUser:output_type -> nodepb.DeleteUserResponse
	14, // 28: nodepb.AuthService.ValidateToken:output_type -> nodepb.TokenResponse
	16, // 29: nodepb.AuthService.RefreshToken:output_type -> nodepb.RefreshTokenResponse
	18, // 30: nodepb.AuthService.VerifyOTP:output_type -> nodepb.VerifyOTPResponse
	20, // 31: nodepb.AuthService.NotifyNewDevice:output_type -> nodepb.NotifyNewDeviceResponse
	22, // 32: nodepb.AuthService.RequestPasswordReset:output_type -> nodepb.PasswordResetResponse
	24, // 33: nodepb.AuthService.EnableMFA:output_type -> nodepb.EnableMFAResponse
	26, // 34: nodepb.AuthService.DisableMFA:output_type -> nodepb.DisableMFAResponse
	28, // 35: nodepb.AuthService.UpdateUserPassword:output_type -> nodepb.UpdateUserPasswordResponse
	32, // 36: nodepb.AuthService.GetUserProfile:output_type -> nodepb.GetUserProfileResponse
	30, // 37: nodepb.AuthService.ForgotPassword:output_type -> nodepb.ForgotPasswordResponse
	34, // 38: nodepb.AuthService.SetCdnPermissions:output_type -> nodepb.SetCdnPermissionsResponse
	39, // 39: nodepb.AuthService.ListAllAdmins:output_type -> nodepb.ListAllAdminsResponse
	37, // 40: nodepb.AuthService.GetAdminByID:output_type -> nodepb.GetAdminInfoResponse
	22, // [22:41] is the sub-list for method output_type
	3,  // [3:22] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
