# configuration du Control Plane (control-plane/config/config.yaml)

server:
  host: "0.0.0.0"           
  grpc_port: 50062
  http_port: 8091
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"

metrics:
  prometheus_enabled: true
  prometheus_port: 9001

scrape_configs:
  - job_name: 'control-plane'
    static_configs:
      - targets: ['control-plane:9001']

auth_service:
  host: auth-service
  port: 50051  

jwt:
  secret_key: ""
  refresh_secret: ""
  access_token_expiry: 1h
  refresh_token_expiry: 7d
  issuer: control-plane

database:
  host: "localhost"
  port: 5443
  user: "cdnadmin"
  password: "cdnpassword"
  name: "control_db"
  sslmode: "disable"  # disable | require | verify-ca | verify-full

redis:
  host: localhost #redis
  port: 6379
  password: ""
  db: 0

metrics:
  prometheus_enabled: true
  prometheus_port: 9090

logging:
  level: "info"     # info | debug | warn | error
  format: "json"    # json | text
  file: logs/app.log

tenancy:
  multi_tenant: true
  default_tenant: "public"

security:
  max_failed_attempts: 5
  lockout_duration: 15m
  allowed_origins:
    - "https://cdncdncdn.com"

tracking:
  enable_ip_logging: true
  enable_user_agent_logging: true

roles_a: ["superadmin"]
roles_b: ["admin", "viewer"]

google_cloud:
  secret_manager:
    gcloud_key: "gcloud-key-json"
  pubsub:
    project_id: "syk-microservices"
    topic_name: "syk-event"
    subscription_name: "notes-subscription"

use_cloud_secrets: false

firebase:
  firebase_api_key: ""
  firebase_credentials: ""


email:
  smtp_host: ""
  smtp_port: ""
  username: ""
  password: ""
  from_email: ""
  from_name: "cdn"

monitoringetat:
  degraded_cpu_threshold: 85.0
  degraded_mem_threshold: 90.0
  critical_cpu_threshold: 95.0
  critical_mem_threshold: 95.0
  max_nodes_per_tenant: 20

temporal:
  enabled: true
  address: "localhost:7233"
  namespace: "cdn-platform"
  task_queue: "cdn-workflows"
  log_history: true
