// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: kube_manager.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	K8SVersion    string                 `protobuf:"bytes,4,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	NodeCount     int32                  `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"` // ex: "bare-metal", "aws", "gcp"
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_kube_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClusterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateClusterRequest) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *CreateClusterRequest) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *CreateClusterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateClusterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ClusterIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterIDRequest) Reset() {
	*x = ClusterIDRequest{}
	mi := &file_kube_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterIDRequest) ProtoMessage() {}

func (x *ClusterIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterIDRequest.ProtoReflect.Descriptor instead.
func (*ClusterIDRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterIDRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ScaleClusterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AdditionalNodes int32                  `protobuf:"varint,2,opt,name=additional_nodes,json=additionalNodes,proto3" json:"additional_nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScaleClusterRequest) Reset() {
	*x = ScaleClusterRequest{}
	mi := &file_kube_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleClusterRequest) ProtoMessage() {}

func (x *ScaleClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleClusterRequest.ProtoReflect.Descriptor instead.
func (*ScaleClusterRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ScaleClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ScaleClusterRequest) GetAdditionalNodes() int32 {
	if x != nil {
		return x.AdditionalNodes
	}
	return 0
}

type DeployAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Values        map[string]string      `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // valeurs du chart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	mi := &file_kube_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{3}
}

func (x *DeployAppRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DeployAppRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *DeployAppRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeployAppRequest) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RestartComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"` // ex: "kubelet", "dns", "scheduler"
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartComponentRequest) Reset() {
	*x = RestartComponentRequest{}
	mi := &file_kube_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartComponentRequest) ProtoMessage() {}

func (x *RestartComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartComponentRequest.ProtoReflect.Descriptor instead.
func (*RestartComponentRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{4}
}

func (x *RestartComponentRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RestartComponentRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *RestartComponentRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	K8SVersion    string                 `protobuf:"bytes,7,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	NodeCount     int32                  `protobuf:"varint,8,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_kube_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{5}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Cluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Cluster) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Cluster) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *Cluster) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Cluster) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Cluster) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Cluster) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ClusterStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterId        string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // ex: provisioning, healthy, degraded, failed
	NodeCount        int32                  `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	ComponentsStatus map[string]string      `protobuf:"bytes,4,rep,name=components_status,json=componentsStatus,proto3" json:"components_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastCheck        string                 `protobuf:"bytes,5,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_kube_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterStatusResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterStatusResponse) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ClusterStatusResponse) GetComponentsStatus() map[string]string {
	if x != nil {
		return x.ComponentsStatus
	}
	return nil
}

func (x *ClusterStatusResponse) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

type ClusterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterListResponse) Reset() {
	*x = ClusterListResponse{}
	mi := &file_kube_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterListResponse) ProtoMessage() {}

func (x *ClusterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterListResponse.ProtoReflect.Descriptor instead.
func (*ClusterListResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterListResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ClusterLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Logs          []string               `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterLogResponse) Reset() {
	*x = ClusterLogResponse{}
	mi := &file_kube_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterLogResponse) ProtoMessage() {}

func (x *ClusterLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterLogResponse.ProtoReflect.Descriptor instead.
func (*ClusterLogResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{8}
}

func (x *ClusterLogResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterLogResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type TenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequest) Reset() {
	*x = TenantRequest{}
	mi := &file_kube_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequest) ProtoMessage() {}

func (x *TenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequest.ProtoReflect.Descriptor instead.
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{9}
}

func (x *TenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_kube_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{10}
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,2,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	AppConfigs    map[string]string      `protobuf:"bytes,3,rep,name=app_configs,json=appConfigs,proto3" json:"app_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterConfigResponse) Reset() {
	*x = ClusterConfigResponse{}
	mi := &file_kube_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigResponse) ProtoMessage() {}

func (x *ClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*ClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterConfigResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterConfigResponse) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *ClusterConfigResponse) GetAppConfigs() map[string]string {
	if x != nil {
		return x.AppConfigs
	}
	return nil
}

type ApplyClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	KubeadmConfig string                 `protobuf:"bytes,2,opt,name=kubeadm_config,json=kubeadmConfig,proto3" json:"kubeadm_config,omitempty"`
	AppConfigs    map[string]string      `protobuf:"bytes,3,rep,name=app_configs,json=appConfigs,proto3" json:"app_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyClusterConfigRequest) Reset() {
	*x = ApplyClusterConfigRequest{}
	mi := &file_kube_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyClusterConfigRequest) ProtoMessage() {}

func (x *ApplyClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyClusterConfigRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ApplyClusterConfigRequest) GetKubeadmConfig() string {
	if x != nil {
		return x.KubeadmConfig
	}
	return ""
}

func (x *ApplyClusterConfigRequest) GetAppConfigs() map[string]string {
	if x != nil {
		return x.AppConfigs
	}
	return nil
}

type ClusterOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*ClusterOperation    `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOperationsResponse) Reset() {
	*x = ClusterOperationsResponse{}
	mi := &file_kube_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOperationsResponse) ProtoMessage() {}

func (x *ClusterOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOperationsResponse.ProtoReflect.Descriptor instead.
func (*ClusterOperationsResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{13}
}

func (x *ClusterOperationsResponse) GetOperations() []*ClusterOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ClusterOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // create, scale, delete, deploy, etc.
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending, success, failed
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOperation) Reset() {
	*x = ClusterOperation{}
	mi := &file_kube_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOperation) ProtoMessage() {}

func (x *ClusterOperation) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOperation.ProtoReflect.Descriptor instead.
func (*ClusterOperation) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterOperation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClusterOperation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterOperation) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ClusterOperation) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type AddClusterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // ex: admin, viewer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClusterUserRequest) Reset() {
	*x = AddClusterUserRequest{}
	mi := &file_kube_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClusterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClusterUserRequest) ProtoMessage() {}

func (x *AddClusterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClusterUserRequest.ProtoReflect.Descriptor instead.
func (*AddClusterUserRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{15}
}

func (x *AddClusterUserRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AddClusterUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddClusterUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ClusterUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ClusterUser         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterUsersResponse) Reset() {
	*x = ClusterUsersResponse{}
	mi := &file_kube_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterUsersResponse) ProtoMessage() {}

func (x *ClusterUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterUsersResponse.ProtoReflect.Descriptor instead.
func (*ClusterUsersResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{16}
}

func (x *ClusterUsersResponse) GetUsers() []*ClusterUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type ClusterUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	AddedAt       string                 `protobuf:"bytes,3,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterUser) Reset() {
	*x = ClusterUser{}
	mi := &file_kube_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterUser) ProtoMessage() {}

func (x *ClusterUser) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterUser.ProtoReflect.Descriptor instead.
func (*ClusterUser) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{17}
}

func (x *ClusterUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClusterUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterUser) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

type UpgradeClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NewK8SVersion string                 `protobuf:"bytes,2,opt,name=new_k8s_version,json=newK8sVersion,proto3" json:"new_k8s_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeClusterRequest) Reset() {
	*x = UpgradeClusterRequest{}
	mi := &file_kube_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeClusterRequest) ProtoMessage() {}

func (x *UpgradeClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeClusterRequest.ProtoReflect.Descriptor instead.
func (*UpgradeClusterRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{18}
}

func (x *UpgradeClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpgradeClusterRequest) GetNewK8SVersion() string {
	if x != nil {
		return x.NewK8SVersion
	}
	return ""
}

type NodeHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthRequest) Reset() {
	*x = NodeHealthRequest{}
	mi := &file_kube_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthRequest) ProtoMessage() {}

func (x *NodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthRequest.ProtoReflect.Descriptor instead.
func (*NodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{19}
}

func (x *NodeHealthRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeHealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type NodeHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthResponse) Reset() {
	*x = NodeHealthResponse{}
	mi := &file_kube_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthResponse) ProtoMessage() {}

func (x *NodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kube_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthResponse.ProtoReflect.Descriptor instead.
func (*NodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_kube_manager_proto_rawDescGZIP(), []int{20}
}

func (x *NodeHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeHealthResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_kube_manager_proto protoreflect.FileDescriptor

const file_kube_manager_proto_rawDesc = "" +
	"\n" +
	"\x12kube_manager.proto\x12\x06kubepb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb0\x02\n" +
	"\x14CreateClusterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1f\n" +
	"\vk8s_version\x18\x04 \x01(\tR\n" +
	"k8sVersion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x05 \x01(\x05R\tnodeCount\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12:\n" +
	"\x04tags\x18\a \x03(\v2&.kubepb.CreateClusterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x10ClusterIDRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"_\n" +
	"\x13ScaleClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12)\n" +
	"\x10additional_nodes\x18\x02 \x01(\x05R\x0fadditionalNodes\"\xe7\x01\n" +
	"\x10DeployAppRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"chart_name\x18\x02 \x01(\tR\tchartName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12<\n" +
	"\x06values\x18\x04 \x03(\v2$.kubepb.DeployAppRequest.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x17RestartComponentRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\xfc\x02\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x1f\n" +
	"\vk8s_version\x18\a \x01(\tR\n" +
	"k8sVersion\x12\x1d\n" +
	"\n" +
	"node_count\x18\b \x01(\x05R\tnodeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12-\n" +
	"\x04tags\x18\v \x03(\v2\x19.kubepb.Cluster.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\x15ClusterStatusResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x05R\tnodeCount\x12`\n" +
	"\x11components_status\x18\x04 \x03(\v23.kubepb.ClusterStatusResponse.ComponentsStatusEntryR\x10componentsStatus\x12\x1d\n" +
	"\n" +
	"last_check\x18\x05 \x01(\tR\tlastCheck\x1aC\n" +
	"\x15ComponentsStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x13ClusterListResponse\x12+\n" +
	"\bclusters\x18\x01 \x03(\v2\x0f.kubepb.ClusterR\bclusters\"G\n" +
	"\x12ClusterLogResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04logs\x18\x02 \x03(\tR\x04logs\",\n" +
	"\rTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"P\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\xe5\x01\n" +
	"\x15ClusterConfigResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x02 \x01(\tR\n" +
	"kubeconfig\x12N\n" +
	"\vapp_configs\x18\x03 \x03(\v2-.kubepb.ClusterConfigResponse.AppConfigsEntryR\n" +
	"appConfigs\x1a=\n" +
	"\x0fAppConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\x19ApplyClusterConfigRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12%\n" +
	"\x0ekubeadm_config\x18\x02 \x01(\tR\rkubeadmConfig\x12R\n" +
	"\vapp_configs\x18\x03 \x03(\v21.kubepb.ApplyClusterConfigRequest.AppConfigsEntryR\n" +
	"appConfigs\x1a=\n" +
	"\x0fAppConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x19ClusterOperationsResponse\x128\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x18.kubepb.ClusterOperationR\n" +
	"operations\"\x88\x01\n" +
	"\x10ClusterOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\"c\n" +
	"\x15AddClusterUserRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"A\n" +
	"\x14ClusterUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.kubepb.ClusterUserR\x05users\"U\n" +
	"\vClusterUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x19\n" +
	"\badded_at\x18\x03 \x01(\tR\aaddedAt\"^\n" +
	"\x15UpgradeClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12&\n" +
	"\x0fnew_k8s_version\x18\x02 \x01(\tR\rnewK8sVersion\"K\n" +
	"\x11NodeHealthRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xab\x01\n" +
	"\x12NodeHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12A\n" +
	"\ametrics\x18\x02 \x03(\v2'.kubepb.NodeHealthResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf1\r\n" +
	"\x12KubeManagerService\x12a\n" +
	"\rCreateCluster\x12\x1c.kubepb.CreateClusterRequest\x1a\x19.kubepb.OperationResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/clusters\x12k\n" +
	"\tDeployApp\x12\x18.kubepb.DeployAppRequest\x1a\x19.kubepb.OperationResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/clusters/{cluster_id}/apps\x12r\n" +
	"\fScaleCluster\x12\x1b.kubepb.ScaleClusterRequest\x1a\x19.kubepb.OperationResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/clusters/{cluster_id}/scale\x12g\n" +
	"\rDeleteCluster\x12\x18.kubepb.ClusterIDRequest\x1a\x19.kubepb.OperationResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/clusters/{cluster_id}\x12u\n" +
	"\x10GetClusterStatus\x12\x18.kubepb.ClusterIDRequest\x1a\x1d.kubepb.ClusterStatusResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/clusters/{cluster_id}/status\x12`\n" +
	"\x14ListClustersByTenant\x12\x15.kubepb.TenantRequest\x1a\x1b.kubepb.ClusterListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/clusters\x12n\n" +
	"\x0eGetClusterLogs\x12\x18.kubepb.ClusterIDRequest\x1a\x1a.kubepb.ClusterLogResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/clusters/{cluster_id}/logs\x12|\n" +
	"\x10RestartComponent\x12\x1f.kubepb.RestartComponentRequest\x1a\x19.kubepb.OperationResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/clusters/{cluster_id}/restart\x12x\n" +
	"\x13ExportClusterConfig\x12\x18.kubepb.ClusterIDRequest\x1a\x1d.kubepb.ClusterConfigResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/clusters/{cluster_id}/export\x12\x7f\n" +
	"\x12ApplyClusterConfig\x12!.kubepb.ApplyClusterConfigRequest\x1a\x19.kubepb.OperationResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/clusters/{cluster_id}/config\x12\x81\x01\n" +
	"\x14GetClusterOperations\x12\x18.kubepb.ClusterIDRequest\x1a!.kubepb.ClusterOperationsResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/clusters/{cluster_id}/operations\x12s\n" +
	"\x10ListClusterUsers\x12\x18.kubepb.ClusterIDRequest\x1a\x1c.kubepb.ClusterUsersResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/clusters/{cluster_id}/users\x12v\n" +
	"\x0eAddClusterUser\x12\x1d.kubepb.AddClusterUserRequest\x1a\x19.kubepb.OperationResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/clusters/{cluster_id}/users\x12x\n" +
	"\x0eUpgradeCluster\x12\x1d.kubepb.UpgradeClusterRequest\x1a\x19.kubepb.OperationResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/clusters/{cluster_id}/upgrade\x12\x80\x01\n" +
	"\rGetNodeHealth\x12\x19.kubepb.NodeHealthRequest\x1a\x1a.kubepb.NodeHealthResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/clusters/{cluster_id}/nodes/{node_id}/healthBCZAgithub.com/thekrauss/Mini-CDN-DDoS-Lab-with-Go/kube-manager/protob\x06proto3"

var (
	file_kube_manager_proto_rawDescOnce sync.Once
	file_kube_manager_proto_rawDescData []byte
)

func file_kube_manager_proto_rawDescGZIP() []byte {
	file_kube_manager_proto_rawDescOnce.Do(func() {
		file_kube_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kube_manager_proto_rawDesc), len(file_kube_manager_proto_rawDesc)))
	})
	return file_kube_manager_proto_rawDescData
}

var file_kube_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_kube_manager_proto_goTypes = []any{
	(*CreateClusterRequest)(nil),      // 0: kubepb.CreateClusterRequest
	(*ClusterIDRequest)(nil),          // 1: kubepb.ClusterIDRequest
	(*ScaleClusterRequest)(nil),       // 2: kubepb.ScaleClusterRequest
	(*DeployAppRequest)(nil),          // 3: kubepb.DeployAppRequest
	(*RestartComponentRequest)(nil),   // 4: kubepb.RestartComponentRequest
	(*Cluster)(nil),                   // 5: kubepb.Cluster
	(*ClusterStatusResponse)(nil),     // 6: kubepb.ClusterStatusResponse
	(*ClusterListResponse)(nil),       // 7: kubepb.ClusterListResponse
	(*ClusterLogResponse)(nil),        // 8: kubepb.ClusterLogResponse
	(*TenantRequest)(nil),             // 9: kubepb.TenantRequest
	(*OperationResponse)(nil),         // 10: kubepb.OperationResponse
	(*ClusterConfigResponse)(nil),     // 11: kubepb.ClusterConfigResponse
	(*ApplyClusterConfigRequest)(nil), // 12: kubepb.ApplyClusterConfigRequest
	(*ClusterOperationsResponse)(nil), // 13: kubepb.ClusterOperationsResponse
	(*ClusterOperation)(nil),          // 14: kubepb.ClusterOperation
	(*AddClusterUserRequest)(nil),     // 15: kubepb.AddClusterUserRequest
	(*ClusterUsersResponse)(nil),      // 16: kubepb.ClusterUsersResponse
	(*ClusterUser)(nil),               // 17: kubepb.ClusterUser
	(*UpgradeClusterRequest)(nil),     // 18: kubepb.UpgradeClusterRequest
	(*NodeHealthRequest)(nil),         // 19: kubepb.NodeHealthRequest
	(*NodeHealthResponse)(nil),        // 20: kubepb.NodeHealthResponse
	nil,                               // 21: kubepb.CreateClusterRequest.TagsEntry
	nil,                               // 22: kubepb.DeployAppRequest.ValuesEntry
	nil,                               // 23: kubepb.Cluster.TagsEntry
	nil,                               // 24: kubepb.ClusterStatusResponse.ComponentsStatusEntry
	nil,                               // 25: kubepb.ClusterConfigResponse.AppConfigsEntry
	nil,                               // 26: kubepb.ApplyClusterConfigRequest.AppConfigsEntry
	nil,                               // 27: kubepb.NodeHealthResponse.MetricsEntry
}
var file_kube_manager_proto_depIdxs = []int32{
	21, // 0: kubepb.CreateClusterRequest.tags:type_name -> kubepb.CreateClusterRequest.TagsEntry
	22, // 1: kubepb.DeployAppRequest.values:type_name -> kubepb.DeployAppRequest.ValuesEntry
	23, // 2: kubepb.Cluster.tags:type_name -> kubepb.Cluster.TagsEntry
	24, // 3: kubepb.ClusterStatusResponse.components_status:type_name -> kubepb.ClusterStatusResponse.ComponentsStatusEntry
	5,  // 4: kubepb.ClusterListResponse.clusters:type_name -> kubepb.Cluster
	25, // 5: kubepb.ClusterConfigResponse.app_configs:type_name -> kubepb.ClusterConfigResponse.AppConfigsEntry
	26, // 6: kubepb.ApplyClusterConfigRequest.app_configs:type_name -> kubepb.ApplyClusterConfigRequest.AppConfigsEntry
	14, // 7: kubepb.ClusterOperationsResponse.operations:type_name -> kubepb.ClusterOperation
	17, // 8: kubepb.ClusterUsersResponse.users:type_name -> kubepb.ClusterUser
	27, // 9: kubepb.NodeHealthResponse.metrics:type_name -> kubepb.NodeHealthResponse.MetricsEntry
	0,  // 10: kubepb.KubeManagerService.CreateCluster:input_type -> kubepb.CreateClusterRequest
	3,  // 11: kubepb.KubeManagerService.DeployApp:input_type -> kubepb.DeployAppRequest
	2,  // 12: kubepb.KubeManagerService.ScaleCluster:input_type -> kubepb.ScaleClusterRequest
	1,  // 13: kubepb.KubeManagerService.DeleteCluster:input_type -> kubepb.ClusterIDRequest
	1,  // 14: kubepb.KubeManagerService.GetClusterStatus:input_type -> kubepb.ClusterIDRequest
	9,  // 15: kubepb.KubeManagerService.ListClustersByTenant:input_type -> kubepb.TenantRequest
	1,  // 16: kubepb.KubeManagerService.GetClusterLogs:input_type -> kubepb.ClusterIDRequest
	4,  // 17: kubepb.KubeManagerService.RestartComponent:input_type -> kubepb.RestartComponentRequest
	1,  // 18: kubepb.KubeManagerService.ExportClusterConfig:input_type -> kubepb.ClusterIDRequest
	12, // 19: kubepb.KubeManagerService.ApplyClusterConfig:input_type -> kubepb.ApplyClusterConfigRequest
	1,  // 20: kubepb.KubeManagerService.GetClusterOperations:input_type -> kubepb.ClusterIDRequest
	1,  // 21: kubepb.KubeManagerService.ListClusterUsers:input_type -> kubepb.ClusterIDRequest
	15, // 22: kubepb.KubeManagerService.AddClusterUser:input_type -> kubepb.AddClusterUserRequest
	18, // 23: kubepb.KubeManagerService.UpgradeCluster:input_type -> kubepb.UpgradeClusterRequest
	19, // 24: kubepb.KubeManagerService.GetNodeHealth:input_type -> kubepb.NodeHealthRequest
	10, // 25: kubepb.KubeManagerService.CreateCluster:output_type -> kubepb.OperationResponse
	10, // 26: kubepb.KubeManagerService.DeployApp:output_type -> kubepb.OperationResponse
	10, // 27: kubepb.KubeManagerService.ScaleCluster:output_type -> kubepb.OperationResponse
	10, // 28: kubepb.KubeManagerService.DeleteCluster:output_type -> kubepb.OperationResponse
	6,  // 29: kubepb.KubeManagerService.GetClusterStatus:output_type -> kubepb.ClusterStatusResponse
	7,  // 30: kubepb.KubeManagerService.ListClustersByTenant:output_type -> kubepb.ClusterListResponse
	8,  // 31: kubepb.KubeManagerService.GetClusterLogs:output_type -> kubepb.ClusterLogResponse
	10, // 32: kubepb.KubeManagerService.RestartComponent:output_type -> kubepb.OperationResponse
	11, // 33: kubepb.KubeManagerService.ExportClusterConfig:output_type -> kubepb.ClusterConfigResponse
	10, // 34: kubepb.KubeManagerService.ApplyClusterConfig:output_type -> kubepb.OperationResponse
	13, // 35: kubepb.KubeManagerService.GetClusterOperations:output_type -> kubepb.ClusterOperationsResponse
	16, // 36: kubepb.KubeManagerService.ListClusterUsers:output_type -> kubepb.ClusterUsersResponse
	10, // 37: kubepb.KubeManagerService.AddClusterUser:output_type -> kubepb.OperationResponse
	10, // 38: kubepb.KubeManagerService.UpgradeCluster:output_type -> kubepb.OperationResponse
	20, // 39: kubepb.KubeManagerService.GetNodeHealth:output_type -> kubepb.NodeHealthResponse
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_kube_manager_proto_init() }
func file_kube_manager_proto_init() {
	if File_kube_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kube_manager_proto_rawDesc), len(file_kube_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kube_manager_proto_goTypes,
		DependencyIndexes: file_kube_manager_proto_depIdxs,
		MessageInfos:      file_kube_manager_proto_msgTypes,
	}.Build()
	File_kube_manager_proto = out.File
	file_kube_manager_proto_goTypes = nil
	file_kube_manager_proto_depIdxs = nil
}
