# configuration du Control Plane (control-plane/config/config.yaml)

server:
  host: "0.0.0.0"           
  grpc_port: 50061
  http_port: 8090
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"


jwt:
  secret_key: ""
  refresh_secret: ""
  access_token_expiry: 1h
  refresh_token_expiry: 7d
  issuer: auth-service

database:
  host: "localhost"
  port: 5442
  user: "cdnadmin"
  password: "cdnpassword"
  name: "auth_db"
  sslmode: "disable"  # disable | require | verify-ca | verify-full

redis:
  host: localhost #redis
  port: 6379
  password: ""
  db: 0

metrics:
  prometheus_enabled: true
  prometheus_port: 9090

logging:
  level: "info"     # info | debug | warn | error
  format: "json"    # json | text
  file: logs/app.log

tenancy:
  multi_tenant: true
  default_tenant: "public"

security:
  max_failed_attempts: 5
  lockout_duration: 15m
  allowed_origins:
    - "https://cdncdncdn.com"

tracking:
  enable_ip_logging: true
  enable_user_agent_logging: true

roles_a: ["superadmin"]
roles_b: ["admin", "viewer"]

google_cloud:
  secret_manager:
    gcloud_key: "gcloud-key-json"
  pubsub:
    project_id: "syk-microservices"
    topic_name: "syk-event"
    subscription_name: "notes-subscription"

use_cloud_secrets: false

firebase:
  firebase_api_key: ""
  firebase_credentials: ""


email:
  smtp_host: ""
  smtp_port: ""
  username: ""
  password: ""
  from_email: ""
  from_name: "Syk"



  